"""add_risk_analysis_fields

Revision ID: 807b0bce12ef
Revises: 7f6b9b878efc
Create Date: 2024-12-24 05:47:34.108471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '807b0bce12ef'
down_revision: Union[str, None] = '7f6b9b878efc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction_patterns', 'avg_transaction_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.add_column('transactions', sa.Column('fraud_probability', sa.Float(), nullable=True))
    op.add_column('transactions', sa.Column('risk_level', sa.String(length=20), nullable=True))
    op.add_column('transactions', sa.Column('pattern_risk_score', sa.Float(), nullable=True))
    op.add_column('transactions', sa.Column('user_behavior_risk_score', sa.Float(), nullable=True))
    op.add_column('transactions', sa.Column('analysis_version', sa.String(length=50), nullable=True))
    op.add_column('transactions', sa.Column('analyzed_at', sa.DateTime(), nullable=True))
    op.alter_column('transactions', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('transactions', 'analyzed_at')
    op.drop_column('transactions', 'analysis_version')
    op.drop_column('transactions', 'user_behavior_risk_score')
    op.drop_column('transactions', 'pattern_risk_score')
    op.drop_column('transactions', 'risk_level')
    op.drop_column('transactions', 'fraud_probability')
    op.alter_column('transaction_patterns', 'avg_transaction_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###
